In [2]:
# !pip uninstall tensorflow

Found existing installation: tensorflow 2.5.0
Uninstalling tensorflow-2.5.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-2.5.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.5.0


In [3]:
# !pip install tensorflow==1.15

     |████████████████████████████████| 412.3 MB 23 kB/s 
     |████████████████████████████████| 50 kB 6.1 MB/s 
     |████████████████████████████████| 503 kB 60.6 MB/s 
     |████████████████████████████████| 3.8 MB 24.7 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7553 sha256=e0395aadc71c06a2b0f40b542e0a23d7472eb3dbd63c6168bab050b5c766cb67
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.5.0
    Uninstalling tensorflow-estimator-2.5.0:
      Successfully uninstalled tensorflow-estimator-2.5.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.5.0
    Uninstalling tensorboard-2.5.0:
      Successfully uninstalled tensorboard-2.5.0
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Succes

In [1]:
import tensorflow as tf

a = tf.constant([5],dtype=tf.float32)
b = tf.constant([10],dtype=tf.float32)
c = tf.constant([2],dtype=tf.float32)

d = a*b+c

print(d)

sess = tf.Session()
result = sess.run(d)
print (result)

Tensor("add:0", shape=(1,), dtype=float32)
[52.]


In [3]:
import tensorflow as tf

# 상수 노드 정의
a = tf.constant(1.0)
b = tf.constant(2.0)
c = tf.constant([ [1.0, 2.0], [3.0, 4.0] ])

print(a)
print(a+b)
print(c)

# 세션 (session) 을 만들고 노드간의 텐서 연산 실행
sess = tf.Session()
print(sess.run([a, b]))
print(sess.run(c))
print(sess.run([a+b]))
print(sess.run(c+1.0)) # broadcast 수행

# 세션 close
sess.close() 

Tensor("Const_3:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)
Tensor("Const_5:0", shape=(2, 2), dtype=float32)
[1.0, 2.0]
[[1. 2.]
 [3. 4.]]
[3.0]
[[2. 3.]
 [4. 5.]]


In [4]:
import tensorflow as tf

input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y,feed_dict={x:input_data})

print(result)

[ 2.  4.  6.  8. 10.]


In [5]:
import tensorflow as tf

input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32)
y = W*x

sess = tf.Session()
result = sess.run(y,feed_dict={x:input_data})

print(result)

FailedPreconditionError: ignored

In [6]:
import tensorflow as tf

input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2],dtype=tf.float32)
y = W*x

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print(result)

[ 2.  4.  6.  8. 10.]


In [8]:
import tensorflow as tf

x = tf.constant([ [1.0,2.0,3.0] ])
w = tf.constant([ [2.0],[2.0],[2.0] ])
y = tf.matmul(x,w)
print(x.get_shape())

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print(result)

(1, 3)
[[12.]]


In [9]:
import tensorflow as tf

x = tf.Variable([ [1.,2.,3.] ], dtype=tf.float32)
w = tf.constant([ [2.],[2.],[2.]], dtype=tf.float32)
y = tf.matmul(x,w)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print(result)

[[12.]]


In [10]:
import tensorflow as tf

input_data = [ [1.,2.,3.],[1.,2.,3.],[2.,3.,4.] ] #3x3 matrix
x = tf.placeholder(dtype=tf.float32,shape=[None,3])
w = tf.Variable([ [2.],[2.],[2.] ], dtype = tf.float32) #3x1 matrix
y = tf.matmul(x,w)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print(result)

[[12.]
 [12.]
 [18.]]


In [11]:
import tensorflow as tf

input_data = [
     [1,1,1],[2,2,2]
    ]
x = tf.placeholder(dtype=tf.float32,shape=[2,3])
w  =tf.Variable([[2],[2],[2]],dtype=tf.float32)
b  =tf.Variable([4],dtype=tf.float32)
y = tf.matmul(x,w)+b

print(x.get_shape())

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y,feed_dict={x:input_data})

print(result)

(2, 3)
[[10.]
 [16.]]


In [12]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)

Mounted at /gdrive


In [13]:
ROOT_PATH = '/gdrive/My Drive/Colab Notebooks/Lectures/'

In [19]:
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf
import numpy as np

In [16]:
filepath = '{}/{}/{}/'.format(ROOT_PATH, 'data', 'mnist')
mnist = input_data.read_data_sets(filepath, one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /gdrive/My Drive/Colab Notebooks/Lectures//data/mnist/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /gdrive/My Drive/Colab Notebooks/Lectures//data/mnist/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /gdrive/My Drive/Colab Notebooks/Lectures//data/mnist/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /gdrive/My Drive/Colab Notebooks/Lectures//data/mnist/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [20]:
print("\ntrain image shape = ", np.shape(mnist.train.images))
print("train label shape = ", np.shape(mnist.train.labels))
print("test image shape = ", np.shape(mnist.test.images))
print("test label shape = ", np.shape(mnist.test.labels))


train image shape =  (55000, 784)
train label shape =  (55000, 10)
test image shape =  (10000, 784)
test label shape =  (10000, 10)


In [24]:
# 신경망 구조 및 하이퍼 파라미터 설정
learning_rate = 0.1 # 학습율
epochs = 100 # 반복횟수
batch_size = 100 # 한번에 입력으로 주어지는 MNIST 데이터 개수
input_nodes = 784 # 입력 층 노드 개수
hidden_nodes = 100 # 은닉 층 노드 개수
output_nodes = 10 # 출력 층 노드 개수

# 입력과 출력을 위한 플레이스홀더(placeholder) 정의
X = tf.placeholder(tf.float32, [None, input_nodes])
T = tf.placeholder(tf.float32, [None, output_nodes])

# 가중치와 바이어스 노드 정의
W2 = tf.Variable(tf.random_normal([input_nodes, hidden_nodes]))
b2 = tf.Variable(tf.random_normal([hidden_nodes]))
W3 = tf.Variable(tf.random_normal([hidden_nodes, output_nodes]))
b3 = tf.Variable(tf.random_normal([output_nodes]))

# 피드포워드 수행 노드 정의
Z2 = tf.matmul(X, W2) + b2 # 은닉층 선형회귀 값 Z2
A2 = tf.nn.relu(Z2) # 은닉층 출력 값 A2
Z3 = logits = tf.matmul(A2, W3) + b3 # 출력층 선형회귀 값 Z3
y = A3 = tf.nn.softmax(Z3) # 출력층 출력 값 A3

# 손실함수 계산 및 가중치, 바이어스 업데이트
cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(logits=Z3, labels=T)
loss = tf.reduce_mean(cross_entropy)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(loss)

# 정확도 검증 노드
predicted_val = tf.equal( tf.argmax(A3, 1), tf.argmax(T, 1) )
accuracy = tf.reduce_mean(tf.cast(predicted_val, dtype=tf.float32))

# MNIST 인식 정확도 검증
with tf.Session() as sess:
	sess.run(tf.global_variables_initializer())

	for I in range(epochs):
		total_batch = int(mnist.train.num_examples / batch_size) # 55,000 / 100

		for step in range(total_batch):
			batch_x, batch_t = mnist.train.next_batch(batch_size)
			loss_val, _ = sess.run([loss, train], feed_dict={X: batch_x, T: batch_t})

			if step % 100 == 0:
				print('step = ', step, ', loss_val = ', loss_val)

		# Accuracy 확인
		test_x_data = mnist.test.images
		test_t_data = mnist.test.labels
		accuracy_val = sess.run(accuracy, feed_dict={X: test_x_data, T: test_t_data})
		print("\nAccuracy = ", accuracy_val)

step =  0 , loss_val =  102.172585
step =  100 , loss_val =  3.9716425
step =  200 , loss_val =  3.0084152
step =  300 , loss_val =  2.6459744
step =  400 , loss_val =  1.0566043
step =  500 , loss_val =  2.128511

Accuracy =  0.8597
step =  0 , loss_val =  0.39965266
step =  100 , loss_val =  1.6609597
step =  200 , loss_val =  0.46147424
step =  300 , loss_val =  0.85154253
step =  400 , loss_val =  1.1934104
step =  500 , loss_val =  0.85407317

Accuracy =  0.8693
step =  0 , loss_val =  0.9349872
step =  100 , loss_val =  0.6614941
step =  200 , loss_val =  0.67386603
step =  300 , loss_val =  0.5770121
step =  400 , loss_val =  0.535161
step =  500 , loss_val =  1.1416191

Accuracy =  0.8736
step =  0 , loss_val =  0.42488164
step =  100 , loss_val =  1.0373819
step =  200 , loss_val =  0.5586882
step =  300 , loss_val =  0.41506532
step =  400 , loss_val =  0.6209833
step =  500 , loss_val =  0.5755485

Accuracy =  0.8793
step =  0 , loss_val =  0.7186689
step =  100 , loss_val =

In [25]:
from datetime import datetime

# mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

print("")
print("train.num = ", mnist.train.num_examples, ", test.num = ", mnist.test.num_examples, ", validation.num = ", mnist.validation.num_examples)

# shape 및 type(mnist) 확인
print("type(mnist) = ", type(mnist), ", type(mnist.train.images) = ", type(mnist.train.images), ", type(mnist.train.labels) = ", type(mnist.train.labels))
print("\ntrain image shape = ", np.shape(mnist.train.images))
print("train label shape = ", np.shape(mnist.train.labels))
print("test image shape = ", np.shape(mnist.test.images))
print("test label shape = ", np.shape(mnist.test.labels))
print("\ntrain image shape = ", mnist.train.images.shape)
print("test image shape = ", mnist.test.images.shape)
print("validation image shape = ", mnist.validation.images.shape)

# train data 정규화 및 label 의 one-hot encoding 확인
# 정규화 확인
print("length of mnist.train.images = ", len(mnist.train.images))
for index in range(len(mnist.train.images)):
	min_val = np.min(mnist.train.images[index])
	max_val = np.max(mnist.train.images[index])

	if min_val < 0.0:
		print("min value is ", min_val, ", index = ", index)
		break

	if max_val > 1.0:
		print("max value is ", max_val, ", index = ", index)
		break

print("")
print(mnist.train.images[0]) # 정규화 확인을 위한 테스트 출력

# one-hot encoding 확인
print("length of mnist.train.images = ", len(mnist.train.labels))

for index in range(len(mnist.train.labels)):
	min_val = np.min(mnist.train.labels[index])
	max_val = np.max(mnist.train.labels[index])
	if min_val < 0.0:
		print("min value is ", min_val, ", index = ", index)
		break
	if max_val > 1.0:
		print("max value is ", max_val, ", index = ", index)
		break

print("")
print(mnist.train.labels[0]) # one-hot encoding 확인을 위한 테스트 출력

# Hyper-Parameter 설정
# 입력노드, 은닉노드, 출력노드, 학습율, 반복횟수, 배치 개수 등 설정
learning_rate = 0.1 # 학습율
epochs = 30 # 반복횟수
batch_size = 100 # 한번에 입력으로 주어지는 MNIST 개수
input_nodes = 784 # 입력노드 개수
hidden_nodes = 100 # 은닉노드 개수
output_nodes = 10 # 출력노드 개수

# 입력과 출력을 위한 플레이스홀더 정의
X = tf.placeholder(tf.float32, [None, input_nodes])
T = tf.placeholder(tf.float32, [None, output_nodes])

# 가중치, 바이어스 정의
W2 = tf.Variable(tf.random_normal([input_nodes, hidden_nodes])) # 은닉층 가중치 노드
b2 = tf.Variable(tf.random_normal([hidden_nodes])) # 은닉층 바이어스 노드
W3 = tf.Variable(tf.random_normal([hidden_nodes, output_nodes])) # 출력층 가중치 노드
b3 = tf.Variable(tf.random_normal([output_nodes])) # 출력층 바이어스 노드
Z2 = tf.matmul(X, W2) + b2 # 선형회귀 선형회귀 값 Z2
A2 = tf.nn.relu(Z2) # 은닉층 출력 값 A2, sigmoid 대신 relu 사용

# 출력층 선형회귀 값 Z3, 즉 softmax 에 들어가는 입력 값
Z3 = logits = tf.matmul(A2, W3) + b3
y = A3 = tf.nn.softmax(Z3)
loss = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits_v2(logits=Z3, labels=T) )
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(loss)

# batch_size X 10 데이터에 대해 argmax 를 통해 행단위로 비교함
predicted_val = tf.equal( tf.argmax(A3, 1), tf.argmax(T, 1) )

# batch_size X 10 의 True, False 를 1 또는 0 으로 변환
accuracy = tf.reduce_mean(tf.cast(predicted_val, dtype=tf.float32))

# index list 출력
accuracy_index = tf.cast(predicted_val, dtype=tf.float32)

# 예측값 처리
predicted_list = tf.argmax(A3, 1)

# Type Check
print('type(predicted_val) = ', type(predicted_val), ', type(accuracy) = ', type(accuracy))
print('type(accuracy_index) =', type(accuracy_index), ', type(predicted_list) = ', type(predicted_list))

with tf.Session() as sess:
	sess.run(tf.global_variables_initializer()) # 변수 노드(tf.Variable) 초기화
	start_time = datetime.now()

	for i in range(epochs): # 50 번 반복수행
		total_batch = int(mnist.train.num_examples / batch_size) # 55,000 / 100

		for step in range(total_batch):
			batch_x_data, batch_t_data = mnist.train.next_batch(batch_size)
			loss_val, _ = sess.run([loss, train],
			feed_dict={X: batch_x_data, T: batch_t_data})

			if step % 100 == 0:
				print("epochs = ", i, ", step = ", step, ", loss_val = ", loss_val)

	end_time = datetime.now()

	print("")
	print("Elapsed Time => ", end_time-start_time)
	print("")

	# Accuracy 확인
	test_x_data = mnist.test.images # 10000 X 784
	test_t_data = mnist.test.labels # 10000 X 10

	accuracy_val = sess.run(accuracy, feed_dict={X: test_x_data, T: test_t_data})
	print('\ntype(accuracy_val) = ', type(accuracy_val), ', Accuracy = ', accuracy_val)

	accuracy_index_val = sess.run(accuracy_index, feed_dict={X: test_x_data, T: test_t_data})
	predicted_list_val = sess.run(predicted_list, feed_dict={X: test_x_data})

	print('========================================================')
	print('type(accuracy_index_val) = ', type(accuracy_index_val), ', len(accuracy_index_val) = ', len(accuracy_index_val))
	print('type(predicted_list_val) = ', type(predicted_list_val), ', len(predicted_list_val) = ', len(predicted_list_val))
	print('')
	print(accuracy_index_val)
	print(predicted_list_val)

	false_data_index = [ index for index, val 	in enumerate(accuracy_index_val) if val == 0 ]

	print('len(false_data_index) = ', len(false_data_index))
	print(false_data_index)

	print('========================================================')
	print('W2, W3, b2, b3 after learning')

	print('=======================================')
	W2_val, W3_val, b2_val, b3_val = sess.run([W2, W3, b2, b3])
	print('W2_val[1] = ' , W2_val[1])
	print('W3_val[2] = ' , W3_val[2])
	print('b2_val[1] = ' , b2_val[1])
	print('b3_val[2] = ' , b3_val[2])

	print('=======================================')


train.num =  55000 , test.num =  10000 , validation.num =  5000
type(mnist) =  <class 'tensorflow.contrib.learn.python.learn.datasets.base.Datasets'> , type(mnist.train.images) =  <class 'numpy.ndarray'> , type(mnist.train.labels) =  <class 'numpy.ndarray'>

train image shape =  (55000, 784)
train label shape =  (55000, 10)
test image shape =  (10000, 784)
test label shape =  (10000, 10)

train image shape =  (55000, 784)
test image shape =  (10000, 784)
validation image shape =  (5000, 784)
length of mnist.train.images =  55000

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.   