# **1. PyTorch Basic**
- Reference의 예제 코드에서 내용 선정 및 발췌 후 정리 및 수정, 보완함
- Reference
  - 파이토치 첫걸음(제이펍) 예제코드

## 1-1. 기본 모듈 임포트

In [2]:
import numpy as np
import torch

## 1-2. GPU 설정하기

In [3]:
# torch.cuda.is_available()를 통해 현재 시스템의 상태를 인식, 지정하면 GPU또는 CPU를 상황에 맞게 적용할 수 있다.
# device='cuda' 또는 device='cuda:0'와 같은 방법으로 직접 지정할 수 있다. (0: GPU의 Index)

USE_CUDA = torch.cuda.is_available()
DEVICE = torch.device("cuda" if USE_CUDA else "cpu")
print(DEVICE)

cuda


## 1-3. 기본 데이터형(텐서) 사용하기

In [6]:
# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4.]])
print(t)

# device를 지정하면 GPU로 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], device='cuda')
print(t)

# dtype을 사용해 데이터형을 지정해 Tensor를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)
print(t)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [7]:
# 0부터 9까지의 수치로 초기화된 1차원 Tensor
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [8]:
#모든 값이 0인 100 x 10 의 Tensor를 작성해서 to메서드로 GPU에 전송
if DEVICE == 'cuda':
  t = torch.zeros(100, 10).to("cuda:0")
else:
  t = torch.zeros(100, 10)

print(t)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],


In [9]:
# 정규 난수로 100 x 10의 Tensor를 작성
t = torch.randn(100, 10)
print(t)

tensor([[ 8.6555e-01, -3.6890e-01, -2.1366e-01,  7.0938e-01, -1.6366e+00,
         -8.0220e-01, -9.0089e-01,  4.4153e-02,  1.2223e+00, -2.6459e-02],
        [ 7.4267e-01,  1.1665e+00, -7.9725e-02,  1.8050e+00, -3.4916e-01,
         -1.6497e+00, -5.7115e-01, -7.9976e-01, -9.1215e-01,  8.6209e-01],
        [-9.0733e-02,  6.3963e-01,  6.4720e-01,  1.1429e+00,  1.2382e+00,
          9.1053e-01,  6.4362e-01,  5.5856e-01,  1.2795e-01,  9.6027e-01],
        [-6.8851e-01, -2.9021e-01,  8.5780e-01,  1.3044e-01,  1.4572e+00,
         -4.2293e-01,  1.3423e+00, -5.9471e-01, -1.6688e+00,  2.5468e+00],
        [-1.1661e+00, -1.9481e+00,  2.1732e+00,  9.8666e-01, -1.4153e+00,
          1.1468e+00,  1.4796e-01,  2.0442e-01, -2.6686e-01,  7.3526e-01],
        [ 1.0506e+00, -7.9669e-01,  9.1563e-01, -3.1918e-01,  1.0565e+00,
         -2.2312e-01, -2.9232e-01,  1.4489e+00, -2.1463e-01,  1.3540e+00],
        [-6.3101e-01,  3.5462e-02, -1.1620e-01, -5.5555e-02,  5.2346e-01,
         -7.5902e-01, -6.1000e-0

In [10]:
# Tensor의 shape은 size 메서드로 취득 가능
t.size()

torch.Size([100, 10])

In [11]:
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1, 2], [3, 4.]])
x = t.numpy()
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [13]:
# GPU上상의 Tensor는 cpu메서드로,
# CPU의 Tensor로 이동(변환)할 필요가 있다
t = torch.tensor([[1, 2], [3, 4.]], device="cuda:0")
x = t.to("cpu").numpy()
x

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [15]:
t = torch.tensor([[1,2,3], [4,5,6.]])

# 스칼라 첨자 지정
print(t[0, 2])

# 슬라이스로 지정
print(t[:, :2])

# 리스트로 지정
print(t[:, [1,2]])

# 마스크 배열을 시용해서 3보다 큰 부분만 선택
print(t[t > 3])

tensor(3.)
tensor([[1., 2.],
        [4., 5.]])
tensor([[2., 3.],
        [5., 6.]])
tensor([4., 5., 6.])


In [16]:
# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100
print(t)

# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200
print(t)      

# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])
tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])
tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


In [19]:
# 길이 3인 벡터
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
print('v=', v)
print('w=', w)
print('----------------------------------------------')

# 2 × 3의 행렬
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])
print('m=', m)
print('----------------------------------------------')

# 벡터와 스칼라의 덧셈
v2 = v + 10
print('v2=', v2)

# 자승도 같은 방식
v2 = v ** 2
print('v2=', v2)

# 동일 길이의 벡터 간 뺄쎔
z = v - w
print('z=', z)

# 여러 가지 조합
u = 2 * v - w / 10 + 6.0
print('u=', u)
print('----------------------------------------------')

# 행렬과 스칼라
m2 = m * 2.0
print('m2=', m2)
# 행렬과 벡터
#(2, 3)인 행렬과 (3,)인 벡터이므로 브로드 캐스트가 작동
m3 = m + v
print('m3=', m3)
# 행렬 간 처리
m4 = m + m
print('m4=', m4)
print('----------------------------------------------')


v= tensor([1., 2., 3.])
w= tensor([ 0., 10., 20.])
----------------------------------------------
m= tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])
----------------------------------------------
v2= tensor([11., 12., 13.])
v2= tensor([1., 4., 9.])
z= tensor([  1.,  -8., -17.])
u= tensor([ 8.,  9., 10.])
----------------------------------------------
m2= tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
m3= tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
m4= tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
----------------------------------------------


In [18]:
# 100 × 10의 테스트 데이터 생성
X = torch.randn(100, 10)
print(X)
print("X=", X)
print('----------------------------------------------')

# 수학 함수를 포함하는 수식
y = X * 2 + torch.abs(X)
print("y=", y)
print('----------------------------------------------')

# 평균치 구하기
m = torch.mean(X)
print('m=', m)
print('----------------------------------------------')

# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()
print('m=', m)
print('----------------------------------------------')

# 집계 결과는 0차원의 Tensor로 item 메서드를 사용해서
# 값을 추출할 수 있다
m_value = m.item()
print('m_value=', m_value)
print('----------------------------------------------')

# 집계는 차원을 지정할 수도 있다. 다음은 행 방향으로 집계해서,
# 열 단위로 평균값을 계산한다
m2 = X.mean(0)
print('m2=', m2)
print('----------------------------------------------')

tensor([[ 7.2740e-01, -3.8103e-01,  1.2323e+00, -1.1125e+00,  2.1223e+00,
         -1.3010e-01,  6.7068e-01, -1.3980e+00, -1.0099e+00,  1.0266e+00],
        [-9.5045e-01, -8.8284e-01, -5.7023e-01, -1.9411e-01, -1.0194e+00,
          1.3391e+00,  2.4549e-01,  1.2038e+00, -1.9821e+00,  1.5756e+00],
        [ 7.2997e-01, -1.4685e+00,  1.1435e+00,  3.0743e-02,  1.5007e-01,
         -3.2701e-01,  8.8925e-01, -6.1868e-01,  8.1744e-01, -8.9386e-01],
        [-1.6616e-01,  2.6470e-01, -5.7589e-01, -9.3633e-02,  2.0412e-01,
          4.8116e-01,  1.3502e+00,  1.4168e-02, -5.8506e-01,  8.3771e-02],
        [-1.5080e+00,  8.5749e-01,  3.5203e-01,  2.0523e-02,  7.1616e-02,
          8.6854e-01, -7.5782e-01, -3.3792e-01, -1.2370e-01,  1.1776e-01],
        [-1.0945e+00,  1.5161e+00,  4.7950e-01,  1.1408e+00, -4.9308e-01,
         -8.8945e-01,  2.6782e-01,  1.2887e-02,  2.6184e-01, -1.8108e-01],
        [ 9.6294e-01,  8.5145e-01,  6.1148e-02,  1.3839e+00, -3.1436e-01,
         -3.6988e-02,  1.0890e+0

In [21]:
x1 = torch.tensor([[1, 2], [3, 4.]]) # 2×2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]]) # 2×3

# 2×2를 4×1로 보여준다
print(x1)
print(x1.view(4, 1))
print('----------------------------------------------')

# -1는 나머지 차원을 나타내며 한 번만 사용할 수 있다
# 아래 예에선 -1을 사용하면 자동으로 4가 된다
print(x1.view(1, -1))
print('----------------------------------------------')

# 2×3을 전치해서 3×2로 만든다
print(x2.t())
print('----------------------------------------------')

# dim=1로 결합하면 2×5의 Tensor를 만든다
torch.cat([x1, x2], dim=1)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
----------------------------------------------
tensor([[1., 2., 3., 4.]])
----------------------------------------------
tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])
----------------------------------------------


tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [22]:
# HWC을 CHW로 변환
# 64×32×3의 데이터가 100개
hwc_img_data = torch.rand(100, 64, 32, 3)
print(hwc_img_data)
print('----------------------------------------------')
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(chw_img_data)

tensor([[[[0.9386, 0.6928, 0.2036],
          [0.4252, 0.8514, 0.6969],
          [0.2262, 0.9862, 0.2277],
          ...,
          [0.9729, 0.6879, 0.8890],
          [0.9282, 0.7060, 0.2665],
          [0.8524, 0.7196, 0.7911]],

         [[0.5145, 0.9374, 0.7375],
          [0.1740, 0.4102, 0.9781],
          [0.7680, 0.3525, 0.7704],
          ...,
          [0.7925, 0.9159, 0.5762],
          [0.5030, 0.0587, 0.0870],
          [0.2088, 0.6539, 0.6863]],

         [[0.7030, 0.0865, 0.0950],
          [0.3045, 0.1143, 0.3443],
          [0.7457, 0.7399, 0.0631],
          ...,
          [0.6490, 0.7909, 0.4203],
          [0.7200, 0.7260, 0.8807],
          [0.4349, 0.6349, 0.2114]],

         ...,

         [[0.4933, 0.3054, 0.8483],
          [0.9276, 0.5396, 0.0068],
          [0.4761, 0.3920, 0.5244],
          ...,
          [0.8612, 0.3420, 0.4676],
          [0.9269, 0.9637, 0.8151],
          [0.4017, 0.3011, 0.9267]],

         [[0.3883, 0.2479, 0.1802],
          [0.4151

In [23]:
m = torch.randn(100, 10)
v = torch.randn(10)
print('m = ', m)
print('v = ', v)

# 내적
d = torch.dot(v, v)
print('d = v·v = ', d)
print('----------------------------------------------')

# 100 × 10의 행렬과 길이 10인 벡터의 곱
# 결과는 길이 100인 벡터
v2 = torch.mv(m, v)
print('v2 = ', v2)
print('----------------------------------------------')

# 행렬곱
m2 = torch.mm(m.t(), m)
print('m2 = ', m2)
print('----------------------------------------------')

# 특이값 분해
u, s, v = torch.svd(m)
print('u = ', u)
print('s = ', s)
print('v = ', v)


m =  tensor([[-1.8975e+00, -1.9829e-01,  1.7223e+00, -5.9035e-01, -7.9090e-01,
          9.6803e-01,  7.8567e-01, -9.1638e-01, -6.6621e-01,  1.3701e+00],
        [ 7.3698e-01, -9.6452e-01, -7.9830e-01, -6.4053e-01,  4.5054e-01,
          3.3361e-01, -1.0393e+00,  7.9701e-01,  1.1382e+00, -2.8283e-01],
        [ 7.0440e-01,  2.2059e-01, -1.1641e+00,  3.9181e-01, -4.3692e-01,
         -1.3592e+00, -7.4545e-01,  2.6004e-01,  1.2281e+00, -2.7179e-01],
        [ 6.0318e-01,  9.1800e-01, -1.9984e+00,  2.1174e+00, -5.7983e-02,
          2.4330e+00,  9.8353e-01, -3.3079e-01, -5.6090e-01,  3.6205e-01],
        [-1.6317e-01, -1.1889e+00, -1.0354e+00,  1.9805e-01, -3.0998e-01,
         -2.0922e-01,  6.7133e-02,  3.9162e-01,  4.5566e-01,  9.6058e-01],
        [ 1.5980e+00,  4.6639e-02,  1.0597e-01,  1.2514e+00,  4.1908e-01,
          3.3722e-01,  6.4257e-01, -1.0691e+00,  1.4748e+00, -4.1095e-01],
        [ 2.8581e-01, -1.0620e+00, -4.0479e-01,  7.1568e-02,  7.4310e-01,
         -9.4992e-01, -1.11

In [24]:
x = torch.randn(100, 3)
print('x = ', x)
print('----------------------------------------------')

# 미분의 변수로 사용하는 경우는 requires_grad를 True로 설정
a = torch.tensor([1, 2, 3.], requires_grad=True)
print('a = ', a)
print('----------------------------------------------')

# 계산을 통해 자동으로 계산 그래프가 구축된다
y = torch.mv(x, a)
o = y.sum()
print('o = ', o)
print('----------------------------------------------')

# 미분을 실행
o.backward()

# 분석 답과 비교
a.grad != x.sum(0)

x =  tensor([[ 1.0667, -1.0013,  0.0738],
        [-0.6318, -0.8667, -0.6509],
        [-0.7167,  1.2600, -2.7644],
        [ 0.2296, -0.7181,  0.5501],
        [ 0.2051,  0.2832, -0.7307],
        [-0.5113,  1.0470, -0.1530],
        [ 0.2402,  0.0606, -0.7700],
        [-0.2238,  0.1013,  0.7168],
        [ 1.9356,  0.7970, -0.9310],
        [ 0.0705,  0.1762, -0.0532],
        [ 0.9764,  1.6867,  0.8483],
        [ 0.0727,  0.7047, -0.5898],
        [-0.9593,  0.3356,  2.3132],
        [ 1.2505, -1.8178,  1.1332],
        [ 1.6168,  0.6804, -1.9254],
        [-0.4781,  1.0307, -0.8953],
        [-1.5940, -1.0399,  0.3399],
        [ 0.7149, -1.8120,  1.4617],
        [-0.6119,  0.0992, -1.6334],
        [ 1.1427,  1.2676,  0.2663],
        [-0.1449, -0.2606,  0.7884],
        [ 0.7484,  1.3881, -1.2272],
        [-0.2550,  0.5097,  0.8220],
        [-1.1844,  0.8233,  0.3923],
        [ 0.3465,  1.3608,  0.2105],
        [-0.7072, -0.9193,  1.1727],
        [-0.1958,  0.8683,  0.467

tensor([True, True, True])

In [25]:
# x는 requires_grad가 False이므로 미분이 계산되지 않는다
x.grad is None

True